package com.kafka.perf.faults;

public enum FaultType {
    F1_CRASH_BEFORE_DB_COMMIT,
    F2_CRASH_AFTER_DB_COMMIT_BEFORE_ACK,
    F3_PARTIAL_BATCH_WRITES,
    F4_DB_CONTAINER_RESTART,
    F5_SLOW_SINK_BACKPRESSURE,
    F6_NETWORK_BOUNDARY_FAULT
}
