########### MODE ###########
producer.mode=TXN_SMALL
# IDEMPOTENT | TXN_SMALL | TXN_LARGE

########### WORKLOAD ###########
num.records=100000
warmup.records=20000
num.iterations=10

########### TRANSACTION ###########
txn.batch.size=1000

########### KAFKA ###########
bootstrap.servers=localhost:9092,localhost:9093,localhost:9094
topic=eos-topic

########### KAFKA PRODUCER SERIALIZERS ###########
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer

########### EOS ESSENTIALS ###########
enable.idempotence=true
acks=all
retries=2147483647
max.in.flight.requests.per.connection=5

########### TRANSACTION ###########
transactional.id=phase1-tx-producer

########### PERFORMANCE ###########
linger.ms=10
batch.size=32768
compression=lz4
buffer.memory=67108864
