########### FAULT INJECTION CONFIGURATION ###########
# Set one fault to true. It will run once after the delay below.

F1=false
F2=false
F3=false
F4=false

# Delay before the enabled fault is injected.
fault.inject.after.minutes=1
