services:
  postgres:
    image: postgres:16
    container_name: pg-sink
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: eos_sink
      POSTGRES_USER: eos
      POSTGRES_PASSWORD: eos
    volumes:
      - pgdata:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "synchronous_commit=on"
      - "-c"
      - "max_connections=100"
    networks:
      - kafka-network

volumes:
  pgdata:

networks:
  kafka-network:
    external: true
    name: kafka-cluster_kafka-network
