{
 "title": "Kafka Monitoring Dashboard",
 "tags": [
  "kafka",
  "baseline",
  "research",
  "throughput"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Kafka Cluster Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg(kafka_cluster_bytes_in_kb_per_sec{ }) / 1024",
     "legendFormat": "bytes in"
    }
   ]
  },
  {
   "title": "Kafka Cluster Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg(kafka_cluster_bytes_out_kb_per_sec{ }) / 1024",
     "legendFormat": "bytes out"
    }
   ]
  },
  {
   "title": "Kafka Cluster CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(kafka_cluster_cpu_percent{ })",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Kafka Cluster Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_cluster_consumer_lag_messages",
     "legendFormat": "cluster lag"
    }
   ]
  }
 ]
}