groups:
- name: kafka_throughput
  interval: 10s
  rules:

  - record: kafka_broker_bytes_in_kb_per_sec
    expr: sum by(instance) (rate(kafka_broker_bytes_in_total[5m])) / 1024

  - record: kafka_broker_bytes_out_kb_per_sec
    expr: sum by(instance) (rate(kafka_broker_bytes_out_total[5m])) / 1024

  - record: kafka_broker_throughput_kb_per_sec
    expr: sum by(instance) (rate(kafka_broker_bytes_in_total[5m]) + rate(kafka_broker_bytes_out_total[5m])) / 1024

  - record: kafka_cluster_bytes_in_kb_per_sec
    expr: sum(rate(kafka_broker_bytes_in_total[5m])) / 1024

  - record: kafka_cluster_bytes_out_kb_per_sec
    expr: sum(rate(kafka_broker_bytes_out_total[5m])) / 1024

  - record: kafka_cluster_throughput_bytes_per_sec
    expr: sum(rate(kafka_broker_bytes_in_total[5m]) + rate(kafka_broker_bytes_out_total[5m]))

  - record: kafka_cluster_messages_per_sec
    expr: sum(rate(kafka_broker_messages_in_total[5m]))


- name: kafka_cpu
  interval: 10s
  rules:

  - record: kafka_broker_cpu_percent
    expr: |-
      sum by(broker) (
        label_replace(
          rate(container_cpu_usage_seconds_total{id=~"/docker/68e2da27dc4129cb28360ce616056f65d76e3bec009cf58abf753b5401a290e8"}[5m]) * 100,
          "broker", "kafka-1", "id", ".*"
        )
        or
        label_replace(
          rate(container_cpu_usage_seconds_total{id=~"/docker/d9ea1ea6791b9b03c4d322a653ead059a77bbf2057eb20cb70540b84126a3290"}[5m]) * 100,
          "broker", "kafka-2", "id", ".*"
        )
        or
        label_replace(
          rate(container_cpu_usage_seconds_total{id=~"/docker/06109a329b6fc5736a20d0f2c7b8f6fdf623de30c8589cf27bb53704029c076c"}[5m]) * 100,
          "broker", "kafka-3", "id", ".*"
        )
        or
        label_replace(
          rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=~"kafka-[0-9]+"}[5m]) * 100,
          "broker", "$1", "container_label_com_docker_compose_service", "(kafka-[0-9]+)"
        )
        or
        label_replace(
          rate(container_cpu_usage_seconds_total{name=~"kafka-[0-9]+"}[5m]) * 100,
          "broker", "$1", "name", "(kafka-[0-9]+)"
        )
      )

  - record: kafka_cluster_cpu_percent
    expr: sum(kafka_broker_cpu_percent)

  - record: kafka_cluster_jvm_cpu_percent
    expr: avg(jvm_process_cpu_load_ratio) * 100


- name: kafka_container_memory
  interval: 10s
  rules:

  - record: kafka_broker_container_memory_mb
    expr: |-
      sum by(broker) (
        label_replace(
          container_memory_usage_bytes{id=~"/docker/68e2da27dc4129cb28360ce616056f65d76e3bec009cf58abf753b5401a290e8"},
          "broker", "kafka-1", "id", ".*"
        )
        or
        label_replace(
          container_memory_usage_bytes{id=~"/docker/d9ea1ea6791b9b03c4d322a653ead059a77bbf2057eb20cb70540b84126a3290"},
          "broker", "kafka-2", "id", ".*"
        )
        or
        label_replace(
          container_memory_usage_bytes{id=~"/docker/06109a329b6fc5736a20d0f2c7b8f6fdf623de30c8589cf27bb53704029c076c"},
          "broker", "kafka-3", "id", ".*"
        )
        or
        label_replace(
          container_memory_usage_bytes{container_label_com_docker_compose_service=~"kafka-[0-9]+"},
          "broker", "$1", "container_label_com_docker_compose_service", "(kafka-[0-9]+)"
        )
        or
        label_replace(
          container_memory_usage_bytes{name=~"kafka-[0-9]+"},
          "broker", "$1", "name", "(kafka-[0-9]+)"
        )
      ) / 1048576

  - record: kafka_cluster_container_memory_gb
    expr: |-
      sum(
        container_memory_usage_bytes{id=~"/docker/(68e2da27dc4129cb28360ce616056f65d76e3bec009cf58abf753b5401a290e8|d9ea1ea6791b9b03c4d322a653ead059a77bbf2057eb20cb70540b84126a3290|06109a329b6fc5736a20d0f2c7b8f6fdf623de30c8589cf27bb53704029c076c)"}
        or
        container_memory_usage_bytes{container_label_com_docker_compose_service=~"kafka-[0-9]+"}
        or
        container_memory_usage_bytes{name=~"kafka-[0-9]+"}
      ) / 1073741824
